const FOOD_DB=[
{name:'Chicken breast',cat:'protein',p:31,c:0,f:3.6,k:165,price:8.2,packageG:1360,tags:['meat','glutenfree'],allergens:[]},
{name:'93% lean ground beef',cat:'protein',p:26,c:0,f:8,k:180,price:12,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Sirloin steak',cat:'protein',p:27,c:0,f:10,k:205,price:17,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Turkey breast',cat:'protein',p:29,c:0,f:2,k:135,price:9.5,packageG:907,tags:['meat','glutenfree'],allergens:[]},
{name:'Shrimp',cat:'protein',p:24,c:.2,f:.4,k:101,price:14,packageG:454,tags:['pescatarian','glutenfree'],allergens:['shellfish']},
{name:'Mahi-mahi',cat:'protein',p:24,c:0,f:1,k:110,price:15,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Salmon',cat:'protein',p:22,c:0,f:12,k:208,price:16,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Tuna',cat:'protein',p:25,c:0,f:1,k:116,price:10,packageG:340,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Egg whites',cat:'protein',p:11,c:.7,f:.2,k:52,price:6,packageG:946,tags:['vegetarian','glutenfree'],allergens:['egg']},
{name:'Whole eggs',cat:'protein',p:13,c:1.1,f:10,k:143,price:5.5,packageG:600,tags:['vegetarian','glutenfree'],allergens:['egg']},
{name:'0% Greek yogurt',cat:'protein',p:10,c:4,f:0,k:59,price:5.5,packageG:907,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Low-fat cottage cheese',cat:'protein',p:12,c:3.4,f:2.3,k:81,price:6,packageG:680,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Firm tofu',cat:'protein',p:14,c:3,f:9,k:144,price:5,packageG:397,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Lentils cooked',cat:'protein',p:9,c:20,f:.4,k:116,price:3.5,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Whey protein',cat:'protein',p:80,c:10,f:5,k:400,price:28,packageG:907,tags:['vegetarian'],allergens:['dairy']},
{name:'Plant protein powder',cat:'protein',p:75,c:12,f:7,k:405,price:30,packageG:700,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Jasmine rice',cat:'carb',p:2.7,c:28,f:.3,k:130,price:2.4,packageG:2268,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Yukon potato',cat:'carb',p:2,c:21,f:.1,k:93,price:2.2,packageG:2268,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Sweet potato',cat:'carb',p:1.6,c:20,f:.1,k:90,price:2.8,packageG:1360,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Oats',cat:'carb',p:16.9,c:66.3,f:6.9,k:389,price:3,packageG:1190,tags:['vegan','vegetarian'],allergens:['gluten-risk']},
{name:'Cream of rice',cat:'carb',p:7,c:80,f:1,k:360,price:5,packageG:794,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Quinoa cooked',cat:'carb',p:4.4,c:21,f:1.9,k:120,price:7,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Banana',cat:'carb',p:1.1,c:23,f:.3,k:89,price:1.5,packageG:1000,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Mixed berries',cat:'carb',p:.8,c:12,f:.4,k:55,price:8,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Apple',cat:'carb',p:.3,c:14,f:.2,k:52,price:3,packageG:1360,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Whole grain bread',cat:'carb',p:12,c:43,f:4,k:250,price:5,packageG:567,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Olive oil',cat:'fat',p:0,c:0,f:100,k:884,price:9,packageG:750,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Avocado',cat:'fat',p:2,c:8.5,f:15,k:160,price:6,packageG:600,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Almond butter',cat:'fat',p:21,c:19,f:56,k:614,price:12,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Peanut butter',cat:'fat',p:25,c:20,f:50,k:588,price:7,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['peanut']},
{name:'Broccoli',cat:'veg',p:2.8,c:7,f:.4,k:35,price:3.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Green beans',cat:'veg',p:1.8,c:7,f:.2,k:35,price:3,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Spinach',cat:'veg',p:3,c:4,f:.4,k:25,price:6,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Mixed vegetables',cat:'veg',p:3,c:10,f:.5,k:55,price:3,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Zucchini',cat:'veg',p:1.2,c:3.1,f:.3,k:17,price:4,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Chicken thigh, skinless',cat:'protein',p:26,c:0,f:8,k:177,price:7.2,packageG:1360,tags:['meat','glutenfree'],allergens:[]},
{name:'99% lean ground turkey',cat:'protein',p:29,c:0,f:1.5,k:135,price:9,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'96% lean ground beef',cat:'protein',p:27,c:0,f:4.5,k:150,price:11,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Pork tenderloin',cat:'protein',p:26,c:0,f:4,k:143,price:9,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Cod',cat:'protein',p:23,c:0,f:.9,k:105,price:12,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Tilapia',cat:'protein',p:26,c:0,f:2.7,k:129,price:9,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Scallops',cat:'protein',p:24,c:5,f:.8,k:111,price:18,packageG:454,tags:['pescatarian','glutenfree'],allergens:['shellfish']},
{name:'Nonfat skyr',cat:'protein',p:11,c:4,f:.2,k:62,price:6.5,packageG:680,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Tempeh',cat:'protein',p:20,c:8,f:11,k:195,price:6,packageG:397,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Seitan',cat:'protein',p:25,c:12,f:2,k:141,price:7,packageG:340,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Black beans cooked',cat:'protein',p:9,c:24,f:.5,k:132,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Chickpeas cooked',cat:'protein',p:9,c:27,f:2.6,k:164,price:3.5,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Basmati rice',cat:'carb',p:2.7,c:28,f:.3,k:130,price:2.7,packageG:2268,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Brown rice cooked',cat:'carb',p:2.6,c:23,f:.9,k:112,price:2.6,packageG:2268,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Pasta cooked',cat:'carb',p:5,c:31,f:1.1,k:158,price:3,packageG:907,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Rice noodles cooked',cat:'carb',p:1.8,c:25,f:.2,k:109,price:4.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Corn tortillas',cat:'carb',p:6,c:45,f:3.5,k:218,price:4,packageG:600,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Bagel',cat:'carb',p:10,c:50,f:1.5,k:250,price:5,packageG:600,tags:['vegetarian'],allergens:['gluten']},
{name:'English muffin',cat:'carb',p:9,c:47,f:2,k:235,price:5,packageG:500,tags:['vegetarian'],allergens:['gluten']},
{name:'Rice cakes',cat:'carb',p:8,c:82,f:3,k:387,price:4,packageG:220,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Pineapple',cat:'carb',p:.5,c:13,f:.1,k:50,price:4,packageG:1000,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Mango',cat:'carb',p:.8,c:15,f:.4,k:60,price:4.5,packageG:1000,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Blueberries',cat:'carb',p:.7,c:14,f:.3,k:57,price:7,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Honey',cat:'carb',p:.3,c:82,f:0,k:304,price:8,packageG:680,tags:['vegetarian','glutenfree'],allergens:[]},
{name:'Walnuts',cat:'fat',p:15,c:14,f:65,k:654,price:11,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Almonds',cat:'fat',p:21,c:22,f:50,k:579,price:10,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Cashews',cat:'fat',p:18,c:30,f:44,k:553,price:11,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Tahini',cat:'fat',p:17,c:21,f:53,k:595,price:9,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['sesame']},
{name:'Chia seeds',cat:'fat',p:17,c:42,f:31,k:486,price:9,packageG:340,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Pumpkin seeds',cat:'fat',p:30,c:11,f:49,k:559,price:10,packageG:340,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Asparagus',cat:'veg',p:2.2,c:3.9,f:.1,k:20,price:5,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Bell peppers',cat:'veg',p:1,c:6,f:.3,k:31,price:5,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Brussels sprouts',cat:'veg',p:3.4,c:9,f:.3,k:43,price:4.5,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Cauliflower',cat:'veg',p:1.9,c:5,f:.3,k:25,price:4,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Carrots',cat:'veg',p:.9,c:10,f:.2,k:41,price:2.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Mushrooms',cat:'veg',p:3.1,c:3.3,f:.3,k:22,price:5,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Romaine lettuce',cat:'veg',p:1.2,c:3.3,f:.3,k:17,price:3,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Rotisserie chicken breast',cat:'protein',p:29,c:0,f:7,k:179,price:10,packageG:850,tags:['meat','glutenfree'],allergens:[]},
{name:'Lean deli turkey',cat:'protein',p:18,c:3,f:2,k:105,price:9,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Lean ham',cat:'protein',p:21,c:1.5,f:5,k:135,price:8.5,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Canadian bacon',cat:'protein',p:20,c:2,f:4,k:124,price:9,packageG:340,tags:['meat','glutenfree'],allergens:[]},
{name:'Bison, lean',cat:'protein',p:28,c:0,f:6,k:170,price:18,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Venison, lean',cat:'protein',p:30,c:0,f:3,k:158,price:18,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Top round beef',cat:'protein',p:29,c:0,f:5,k:164,price:12,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Eye of round beef',cat:'protein',p:29,c:0,f:4,k:155,price:12,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Flank steak',cat:'protein',p:27,c:0,f:8,k:183,price:15,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Pork loin',cat:'protein',p:27,c:0,f:5,k:160,price:8.5,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Turkey tenderloin',cat:'protein',p:29,c:0,f:2,k:134,price:10,packageG:680,tags:['meat','glutenfree'],allergens:[]},
{name:'Chicken sausage, lean',cat:'protein',p:17,c:3,f:9,k:161,price:9,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Turkey sausage, lean',cat:'protein',p:19,c:2,f:8,k:156,price:8.5,packageG:454,tags:['meat','glutenfree'],allergens:[]},
{name:'Canned chicken breast',cat:'protein',p:25,c:0,f:2,k:118,price:7,packageG:354,tags:['meat','glutenfree'],allergens:[]},
{name:'Canned tuna in water',cat:'protein',p:26,c:0,f:1,k:116,price:7,packageG:340,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Sardines',cat:'protein',p:25,c:0,f:11,k:208,price:8,packageG:340,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Crab meat',cat:'protein',p:19,c:0,f:1.5,k:90,price:18,packageG:454,tags:['pescatarian','glutenfree'],allergens:['shellfish']},
{name:'Lobster',cat:'protein',p:21,c:1,f:.9,k:96,price:24,packageG:454,tags:['pescatarian','glutenfree'],allergens:['shellfish']},
{name:'Pollock',cat:'protein',p:23,c:0,f:1,k:105,price:9,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Haddock',cat:'protein',p:24,c:0,f:.7,k:107,price:11,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Trout',cat:'protein',p:22,c:0,f:7,k:154,price:14,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Swordfish',cat:'protein',p:23,c:0,f:8,k:172,price:18,packageG:454,tags:['pescatarian','glutenfree'],allergens:['fish']},
{name:'Egg substitute',cat:'protein',p:10,c:2,f:0,k:48,price:6.5,packageG:946,tags:['vegetarian','glutenfree'],allergens:['egg']},
{name:'2% Greek yogurt',cat:'protein',p:10,c:4,f:2,k:74,price:6,packageG:907,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Nonfat cottage cheese',cat:'protein',p:12,c:4,f:.5,k:72,price:6,packageG:680,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Part-skim mozzarella',cat:'protein',p:24,c:3,f:16,k:254,price:8,packageG:454,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Reduced-fat cheese',cat:'protein',p:28,c:4,f:17,k:280,price:8,packageG:454,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Kefir, low-fat',cat:'protein',p:4,c:5,f:1,k:45,price:6,packageG:946,tags:['vegetarian','glutenfree'],allergens:['dairy']},
{name:'Soy yogurt, unsweetened',cat:'protein',p:5,c:4,f:3,k:63,price:6,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Edamame cooked',cat:'protein',p:12,c:9,f:5,k:121,price:5,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Textured vegetable protein',cat:'protein',p:50,c:30,f:1,k:327,price:7,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Soy curls',cat:'protein',p:33,c:33,f:7,k:327,price:9,packageG:340,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Pea protein isolate',cat:'protein',p:80,c:7,f:5,k:393,price:27,packageG:700,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Soy protein isolate',cat:'protein',p:88,c:4,f:1,k:377,price:24,packageG:700,tags:['vegan','vegetarian','glutenfree'],allergens:['soy']},
{name:'Kidney beans cooked',cat:'protein',p:9,c:23,f:.5,k:127,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Pinto beans cooked',cat:'protein',p:9,c:26,f:.7,k:143,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Navy beans cooked',cat:'protein',p:8,c:26,f:.6,k:140,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Great northern beans cooked',cat:'protein',p:9,c:21,f:.5,k:118,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Split peas cooked',cat:'protein',p:8,c:21,f:.4,k:118,price:3,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Lupini beans',cat:'protein',p:16,c:10,f:3,k:119,price:6,packageG:425,tags:['vegan','vegetarian','glutenfree'],allergens:['legume']},
{name:'Hemp hearts',cat:'protein',p:32,c:9,f:49,k:553,price:12,packageG:340,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Protein pasta cooked',cat:'protein',p:13,c:31,f:2,k:192,price:5.5,packageG:907,tags:['vegetarian'],allergens:['gluten']},
{name:'Low-carb tortilla',cat:'carb',p:12,c:30,f:7,k:230,price:6,packageG:400,tags:['vegetarian'],allergens:['gluten']},
{name:'Couscous cooked',cat:'carb',p:3.8,c:23,f:.2,k:112,price:3.5,packageG:907,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Barley cooked',cat:'carb',p:2.3,c:28,f:.4,k:123,price:3,packageG:907,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Farro cooked',cat:'carb',p:5,c:26,f:1,k:130,price:5,packageG:907,tags:['vegan','vegetarian'],allergens:['gluten']},
{name:'Polenta cooked',cat:'carb',p:2,c:14,f:.4,k:70,price:3,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'White potato',cat:'carb',p:2,c:20,f:.1,k:87,price:2.2,packageG:2268,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Butternut squash',cat:'carb',p:1,c:12,f:.1,k:45,price:3.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Grapes',cat:'carb',p:.7,c:18,f:.2,k:69,price:5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Orange',cat:'carb',p:.9,c:12,f:.1,k:47,price:3,packageG:1360,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Strawberries',cat:'carb',p:.7,c:8,f:.3,k:32,price:5,packageG:680,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Dates',cat:'carb',p:2,c:75,f:.2,k:282,price:8,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Maple syrup',cat:'carb',p:0,c:67,f:0,k:268,price:9,packageG:355,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Pistachios',cat:'fat',p:20,c:28,f:45,k:562,price:12,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Pecans',cat:'fat',p:9,c:14,f:72,k:691,price:12,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:['tree nuts']},
{name:'Sunflower seeds',cat:'fat',p:21,c:20,f:51,k:584,price:7,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Sunflower seed butter',cat:'fat',p:18,c:20,f:55,k:617,price:8,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Flaxseed',cat:'fat',p:18,c:29,f:42,k:534,price:6,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Olives',cat:'fat',p:.8,c:6,f:15,k:145,price:6,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Cucumber',cat:'veg',p:.7,c:3.6,f:.1,k:15,price:2.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Cabbage',cat:'veg',p:1.3,c:6,f:.1,k:25,price:2.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Kale',cat:'veg',p:2.9,c:4.4,f:1.5,k:35,price:4,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Tomatoes',cat:'veg',p:.9,c:3.9,f:.2,k:18,price:4,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Onions',cat:'veg',p:1.1,c:9,f:.1,k:40,price:2.5,packageG:907,tags:['vegan','vegetarian','glutenfree'],allergens:[]},
{name:'Snap peas',cat:'veg',p:2.8,c:7.6,f:.2,k:42,price:5,packageG:454,tags:['vegan','vegetarian','glutenfree'],allergens:[]}
];

const EXERCISES=[
{name:'Goblet Squat',m:'quads',eq:['dumbbells'],avoid:['knee']},{name:'Leg Press',m:'quads',eq:['machines'],avoid:['knee']},{name:'Back Squat',m:'quads',eq:['barbell'],avoid:['knee','low back']},{name:'Hack Squat',m:'quads',eq:['machines'],avoid:['knee']},{name:'Leg Extension',m:'quads',eq:['machines'],avoid:['knee']},
{name:'Romanian Deadlift',m:'hamstrings',eq:['barbell','dumbbells'],avoid:['low back']},{name:'Seated Leg Curl',m:'hamstrings',eq:['machines'],avoid:[]},{name:'Lying Leg Curl',m:'hamstrings',eq:['machines'],avoid:[]},
{name:'Hip Thrust',m:'glutes',eq:['barbell','machines'],avoid:['hip']},{name:'Walking Lunge',m:'glutes',eq:['dumbbells','bodyweight'],avoid:['knee','hip']},{name:'Cable Kickback',m:'glutes',eq:['cables'],avoid:['hip']},
{name:'DB Bench Press',m:'chest',eq:['dumbbells','bench'],avoid:['shoulder']},{name:'Machine Chest Press',m:'chest',eq:['machines'],avoid:['shoulder']},{name:'Push-up',m:'chest',eq:['bodyweight'],avoid:['shoulder','wrist']},{name:'Incline DB Press',m:'chest',eq:['dumbbells','bench'],avoid:['shoulder']},{name:'Cable Fly',m:'chest',eq:['cables'],avoid:['shoulder']},
{name:'Lat Pulldown',m:'back',eq:['cables','machines'],avoid:['shoulder']},{name:'Chest Supported Row',m:'back',eq:['dumbbells','bench'],avoid:[]},{name:'Cable Row',m:'back',eq:['cables'],avoid:[]},{name:'Pull-up',m:'back',eq:['pull-up bar','bodyweight'],avoid:['shoulder','elbow']},{name:'One-arm DB Row',m:'back',eq:['dumbbells'],avoid:['low back']},
{name:'DB Lateral Raise',m:'delts',eq:['dumbbells'],avoid:['shoulder']},{name:'Cable Lateral Raise',m:'delts',eq:['cables'],avoid:['shoulder']},{name:'Machine Shoulder Press',m:'delts',eq:['machines'],avoid:['shoulder']},{name:'Rear Delt Fly',m:'delts',eq:['machines','dumbbells'],avoid:['shoulder']},
{name:'Cable Curl',m:'biceps',eq:['cables'],avoid:['elbow']},{name:'DB Curl',m:'biceps',eq:['dumbbells'],avoid:['elbow']},{name:'Rope Pressdown',m:'triceps',eq:['cables'],avoid:['elbow']},{name:'DB Skullcrusher',m:'triceps',eq:['dumbbells','bench'],avoid:['elbow']},
{name:'Standing Calf Raise',m:'calves',eq:['machines','bodyweight'],avoid:[]},{name:'Plank',m:'core',eq:['bodyweight'],avoid:['low back']},{name:'Cable Crunch',m:'core',eq:['cables'],avoid:[]}
];
const EQUIPMENT=['bodyweight','dumbbells','barbell','bench','cables','machines','pull-up bar','bands','cardio machine'];
const STORE_MULTIPLIERS={Aldi:.88,Walmart:.94,Costco:.90,Target:1.05,Publix:1.12,'Whole Foods':1.28,'Trader Joes':1.02};
